aliases = {
    "c": "show cmds",
    "cfg": "show config",
    "e": "ed",
    "f": "find",
    "fl": "show fleet",
    "h": "help",
    "ps": "show tasks",
    "s": "show",
    "v": "show version"
}
classes = [
    "ob.Cfg",
    "ob.Default",
    "ob.Object",
    "ob.clock.Repeater",
    "ob.clock.Timer",
    "ob.clock.Timers",
    "ob.command.Command",
    "ob.command.Token",
    "ob.db.Db",
    "ob.fleet.Fleet",
    "ob.handler.Event",
    "ob.handler.Handler",
    "ob.kernel.Kernel",
    "ob.loader.Loader",
    "ob.user.User",
    "ob.user.Users",
    "obot.Bot",
    "obot.entry.Log",
    "obot.entry.Todo",
    "obot.irc.Cfg",
    "obot.irc.DCC",
    "obot.irc.DEvent",
    "obot.irc.IRC",
    "obot.mbox.Email",
    "obot.rss.Cfg",
    "obot.rss.Feed",
    "obot.rss.Fetcher",
    "obot.rss.Rss",
    "obot.rss.Seen",
    "obot.udp.Cfg",
    "obot.udp.UDP",
    "obot.xmpp.Cfg",
    "obot.xmpp.Event",
    "obot.xmpp.XMPP"
]
names = {
    "cfg": "ob.Cfg",
    "default": "ob.Default",
    "object": "ob.Object",
    "repeater": "ob.clock.Repeater",
    "timer": "ob.clock.Timer",
    "timers": "ob.clock.Timers",
    "command": "ob.command.Command",
    "token": "ob.command.Token",
    "db": "ob.db.Db",
    "fleet": "ob.fleet.Fleet",
    "event": "ob.handler.Event",
    "handler": "ob.handler.Handler",
    "kernel": "ob.kernel.Kernel",
    "loader": "ob.loader.Loader",
    "user": "ob.user.User",
    "users": "ob.user.Users",
    "bot": "obot.Bot",
    "log": "obot.entry.Log",
    "todo": "obot.entry.Todo",
    "dcc": "obot.irc.DCC",
    "devent": "obot.irc.DEvent",
    "irc": "obot.irc.IRC",
    "email": "obot.mbox.Email",
    "feed": "obot.rss.Feed",
    "fetcher": "obot.rss.Fetcher",
    "rss": "obot.rss.Rss",
    "seen": "obot.rss.Seen",
    "udp": "obot.udp.UDP",
    "xmpp": "obot.xmpp.XMPP"
}
modules = {
    "cmds": "ob.cmds",
    "find": "ob.db",
    "load": "ob.loader",
    "unload": "ob.loader",
    "show": "ob.show",
    "meet": "ob.user",
    "log": "obot.entry",
    "todo": "obot.entry",
    "cor": "obot.mbox",
    "mbox": "obot.mbox",
    "delete": "obot.rss",
    "fetch": "obot.rss",
    "rss": "obot.rss",
    "wisdom": "obot.wisdom"
}
