#!/bin/sh
### BEGIN INIT INFO
# Provides:          obot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pure python3 channel bot
# Description: OBOT is a IRC/XMPP bot you can use to display RSS feeds, uses a timestamped 
#              JSON file backend to provide persistence, makes it possible to program your
#              own module enabling your own commands, is in the Public Domain and contains
#              no copyright or LICENSE.
### END INIT INFO

# Author: Bart Thate <bthate@dds.nl>

DESC="pure python3 channel bot"
DAEMON=/usr/bin/obot

case "$1" in
start)  log_daemon_msg "Starting obot" "obot"
        sudo -u ubuntu /usr/bin/streamripper http://184.154.58.146:29378/ch18_56.mp3 --quiet -s -a -d ~ &

        ;;
stop)   log_daemon_msg "Stopping obot" "obot"
        pkill streamripper
        RETVAL=0

        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting obot" "obot"
        $0 stop
        $0 start
        ;;
*)
